package main

import (
	"bytes"
	genz2 "github.com/Joffref/genz/genz"
	"github.com/Joffref/genz/genz/cli"
	"github.com/Joffref/genz/genz/models"
	"io"
)

func main() {
	err := cli.NewCommandFromGenerator("validator", MyCustomGenerator).Execute()
	if err != nil {
		return
	}
}

func MyCustomGenerator(file io.Writer, element models.ParsedElement) error {
	code := genz2.NewCode(file, element.PackageName).
		WithHeaderComments("File generated by GenZ with template validator").
		WithImports("fmt", "unicode").
		WithDeclarations(
			genz2.Function("Validate").
				WithReceiver("v", element.Type.InternalName, false).
				WithReturns("error").
				WithBody(body(element.Element)),
		)
	err := code.Generate()
	if err != nil {
		return err
	}
	return nil
}

func body(element models.Element) string {
	var buf bytes.Buffer
	for _, attribute := range element.Attributes {
		if attribute.Type.InternalName == "string" {
			for _, comment := range attribute.Comments {
				if comment == "+required" {
					buf.WriteString("if v." + attribute.Name + " == \"\" {\n")
					buf.WriteString("return fmt.Errorf(\"attribute '" + attribute.Name + "' must be set\")\n")
					buf.WriteString("}\n")
				}
				if comment == "+startsWithCapital" {
					buf.WriteString("if v." + attribute.Name + " != \"\" && !unicode.IsUpper(rune(v." + attribute.Name + "[0])) {\n")
					buf.WriteString("return fmt.Errorf(\"attribute '" + attribute.Name + "' should start with a capital letter\")\n")
					buf.WriteString("}\n")
				}
			}
		}
	}
	buf.WriteString("return nil")
	return buf.String()
}
